title: Card group with heading
label: Card group with heading
status: ready
preview: '@preview-bg-padded'
display:
  min-height: 650px
context:
  cardHeading:
    text: Colleague stories
  heading3:
    text: We’re celebrating LGBT history month
  paragraph:
    text: We’re also asking all Co-op colleagues which Pride events they’d like to get involved in.
